### ISSUE TITLE
public_suffix-4.0.6 not found when using ArchivesSpace 3.3.0

### ISSUE THREAD

**Issue by VNCAIT** [lyrasis/aspace-oauth#28]
INFO: An exception happened during JRuby-Rack startup
Could not find public_suffix-4.0.6 in any of the sources
--- System
jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1 Java HotSpot(TM) 64-Bit Server VM 25.301-b09 on 1.8.0_301-b09 +jit [mswin32-x86_64]
Time: 2022-09-19 10:19:49 -0500
Server: jetty/9.4.44.v20210927
jruby.home: uri:classloader://META-INF/jruby.home

--- Context Init Parameters:
jruby.max.runtimes = 1
jruby.min.runtimes = 1
public.root = /
rails.env = production

--- Backtrace
Bundler::GemNotFound: Could not find public_suffix-4.0.6 in any of the sources
       materialize at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86
              map! at org/jruby/RubyArray.java:2621
       materialize at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80
             specs at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170
         specs_for at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:237
   requested_specs at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:226
   requested_specs at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:101
             setup at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:20
             setup at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler.rb:149
            <main> at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20
        with_level at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136
           silence at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88
            <main> at G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20
           require at org/jruby/RubyKernel.java:974
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:158
            <main> at G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF/config/boot.rb:10
           require at org/jruby/RubyKernel.java:974
           require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
  load_environment at uri:classloader:/jruby/rack/rails/environment3.rb:23
  load_environment at uri:classloader:/jruby/rack/rails_booter.rb:83
            <main> at <script>:1
      start_server at G:\archivesspace\launcher\launcher.rb:90
              main at G:\archivesspace\launcher\launcher.rb:149
            <main> at G:\archivesspace\launcher\launcher.rb:242

--- RubyGems
Gem.dir: G:/archivesspace/gems
Gem.path:
G:/archivesspace/gems
G:/archivesspace/plugins/aspace-oauth/gems
Activated gems:
  did_you_mean-1.2.1
  fileutils-1.1.0
  bundler-2.1.4

--- Bundler
Bundler.bundle_path: G:/archivesspace/gems
Bundler.root: G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF
Gemfile: G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF/Gemfile
Settings:
  jobs = 8
  without = [:test, :development, :doc]
  gemfile = G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF/Gemfile

--- JRuby-Rack Config
compat_version = 
default_logger = org.jruby.rack.logging.StandardOutLogger@1e84a463
equals = <error: >
err = java.io.PrintStream@ee021ff
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size = 
initial_runtimes = 1
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.ServletContextLogger@299e83fd
logger_class_name = servlet_context
logger_name = jruby.rack
maximum_memory_buffer_size = 
maximum_runtimes = 1
num_initializer_threads = 
out = java.io.PrintStream@72327399
rackup = 
rackup_path = 
rewindable = true
runtime_arguments = 
runtime_environment = 
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = ServletContext@o.e.j.w.WebAppContext@348a2f49{/,file:///G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/,STARTING}{G:\archivesspace/wars/frontend.war}
throw_init_exception = false

Sep 19, 2022 10:19:49 AM org.eclipse.jetty.server.handler.ContextHandler$Context log

WARNING: ERROR: initialization failed

org.jruby.rack.RackInitializationException: Could not find public_suffix-4.0.6 in any of the sources
	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'

	from org/jruby/RubyArray.java:2621:in `map!'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in requested_specs'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <main>'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'

	from G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>'

	from org/jruby/RubyKernel.java:974:in `require'

	from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:158:in `require'

	from G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF/config/boot.rb:10:in `<main>'

	from org/jruby/RubyKernel.java:974:in `require'

	from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require'

	from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `load_environment'

	from uri:classloader:/jruby/rack/rails_booter.rb:83:in `load_environment'

	from <script>:1:in `<main>'

	from G:\archivesspace\launcher\launcher.rb:90:in `start_server'

	from G:\archivesspace\launcher\launcher.rb:149:in `main'

	from G:\archivesspace\launcher\launcher.rb:242:in `<main>'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)

	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)

	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)

	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1067)

	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)

	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:996)

	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)

	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)

	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)

	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)

	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)

	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)

	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)

	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)

	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)

	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)

	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)

	at org.eclipse.jetty.server.Server.start(Server.java:423)

	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)

	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)

	at org.eclipse.jetty.server.Server.doStart(Server.java:387)

	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:441)

	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:305)

	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32)

	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:142)

	at G_3a_.archivesspace.launcher.launcher.invokeOther132:start(G:\archivesspace\launcher\launcher.rb:90)

	at G_3a_.archivesspace.launcher.launcher.RUBY$method$start_server$1(G:\archivesspace\launcher\launcher.rb:90)

	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)

	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:192)

	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:419)

	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:237)

	at G_3a_.archivesspace.launcher.launcher.invokeOther210:start_server(G:\archivesspace\launcher\launcher.rb:149)

	at G_3a_.archivesspace.launcher.launcher.RUBY$method$main$6(G:\archivesspace\launcher\launcher.rb:149)

	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:156)

	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:355)

	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)

	at G_3a_.archivesspace.launcher.launcher.invokeOther303:main(G:\archivesspace\launcher\launcher.rb:242)

	at G_3a_.archivesspace.launcher.launcher.RUBY$script(G:\archivesspace\launcher\launcher.rb:242)

	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)

	at org.jruby.ir.Compiler$1.load(Compiler.java:89)

	at org.jruby.Ruby.runScript(Ruby.java:1205)

	at org.jruby.Ruby.runNormally(Ruby.java:1128)

	at org.jruby.Ruby.runNormally(Ruby.java:1146)

	at org.jruby.Ruby.runFromMain(Ruby.java:958)

	at org.jruby.Main.doRunFromMain(Main.java:400)

	at org.jruby.Main.internalRun(Main.java:292)

	at org.jruby.Main.run(Main.java:234)

	at org.jruby.Main.main(Main.java:206)

Caused by: org.jruby.exceptions.StandardError: (GemNotFound) Could not find public_suffix-4.0.6 in any of the sources

	at RUBY.materialize(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86)

	at org.jruby.RubyArray.map!(org/jruby/RubyArray.java:2621)

	at RUBY.materialize(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80)

	at RUBY.specs(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:170)

	at RUBY.specs_for(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:237)

	at RUBY.requested_specs(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/definition.rb:226)

	at RUBY.requested_specs(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:101)

	at RUBY.setup(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:20)

	at RUBY.setup(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler.rb:149)

	at RUBY.<main>(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20)

	at RUBY.with_level(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136)

	at RUBY.silence(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88)

	at RUBY.<main>(G:/archivesspace/gems/gems/bundler-2.1.4/lib/bundler/setup.rb:20)

	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:974)

	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:158)

	at RUBY.<main>(G:/archivesspace/data/tmp/jetty-0_0_0_0-7080-frontend_war-_-any-1764348607246849407/webapp/WEB-INF/config/boot.rb:10)

	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:974)

	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83)

	at RUBY.load_environment(uri:classloader:/jruby/rack/rails/environment3.rb:23)

	at RUBY.load_environment(uri:classloader:/jruby/rack/rails_booter.rb:83)

	at RUBY.<main>(<script>:1)

	at G_3a_.archivesspace.launcher.launcher.start_server(G:\archivesspace\launcher\launcher.rb:90)

	at G_3a_.archivesspace.launcher.launcher.main(G:\archivesspace\launcher\launcher.rb:149)

	at G_3a_.archivesspace.launcher.launcher.<main>(G:\archivesspace\launcher\launcher.rb:242)

**Comment by VNCAIT** [comment]
Next release should fix this.
